#!/bin/sh
# Installs a git pre-commit hook that runs `npm run build` before every
# commit and re-stages the generated content.js / drawvinism.user.js, so
# they're always in sync with src/drawvinism-core.js. Run this once after
# cloning: sh scripts/install-hooks.sh

set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOK="$ROOT/.git/hooks/pre-commit"

cat > "$HOOK" <<'EOF'
#!/bin/sh
# Auto-generated by scripts/install-hooks.sh — do not edit by hand.
node "$(git rev-parse --show-toplevel)/scripts/build.js" || exit 1
git add content.js drawvinism.user.js
EOF

chmod +x "$HOOK"
echo "Installed pre-commit hook at $HOOK"
